---
#- name: Make sure latest EPEL repo is installed
#  yum:
#    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#    state: latest
#    disable_gpg_check: yes

#- name: Install postgres repository for 9.4
#  yum:
#    name: "(( postgresq94_repository_url }}"
#    state: present
#    disable_gpg_check: yes

- name: Install postgres 9.4 packages on RHEL 7
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - rh-postgresql94
    - rh-postgresql94-runtime
    - rh-postgresql94-scldevel
    - rh-postgresql94-postgresql-devel
    - rh-postgresql94-postgresql-libs
    - rh-postgresql94-postgresql-static
    - rh-postgresql94-postgresql-plpython
    - rh-postgresql94-postgresql-contrib

- name: Install postgres 9.6 repo
  yum_repository:
    name: postgresql9.6
    description: postgresql 9.6 repo
    baseurl: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7.9-x86_64/
    gpgcheck: no

- name: Install postgres 9.6 packages on RHEL 7
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - postgresql96
    - postgresql96-libs
    - postgresql96-devel
    - postgresql96-docs
    - postgresql96-contrib

- name: Install postgres 10.x repo
  yum_repository:
    name: postgresql10.x
    description: postgresql 10.x repo
    baseurl: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/
    gpgcheck: no

- name: Install postgres 10.x packages on RHEL 7
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql10
    - postgresql10-libs
    - postgresql10-odbc
    - postgresql10-devel
    - postgresql10-docs
    - postgresql10-contrib

- name: create symlink /usr/pgsql -> /usr/pgsql-10
  file:
    src: /usr/pgsql-10
    dest: /usr/pgsql
    state: link
  tags:
    - postgres_client

- name: Install postgres repository
  yum:
    name: "{{ postgres_repository_url }}"
    state: present
    disable_gpg_check: yes
  when: postgres_install_repository
  tags:
    - postgres_client

- name: Install postgres repository key
  rpm_key:
    key: "{{ postgres_repository_key_url }}"
    state: present
  when: postgres_install_repository
  tags:
    - postgres_client

- name: Ensure older versions are removed
  yum:
    name: "{{ item }}"
    state: absent
    disablerepo: "{{ postgres_repository_name }}"
  ignore_errors: yes
  with_items: "{{ postgres_old_packages }}"
  when: clean_postgresql
  tags:
    - postgres_client

## Repo/Packages for 9.4 Not Available anymore
#- name: Add 94 yum repo
#  yum_repository:
#    name: postgres94
#    description: postgresql 94 repo for RHEL 7
#    baseurl: https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-7-x86_64/

#- name: Install postgres packages
#  yum:
#    name: "{{ item }}"
#    state: present
##   state: latest
#    disable_gpg_check: yes
#  with_items: "{{ postgres_packages }}"
#  tags:
#    - postgres_client

- name: Install gis postgres packages
  yum:
    name: "{{ item }}"
    state: present
#   state: latest
    disable_gpg_check: yes
  with_items: "{{ postgres_gis_packages }}"
  ignore_errors: True
  tags:
    - postgres_client

- name: Check if include link exists
  stat:
    path: /usr/include/pgsql
  register: lpgsqlinclude

# Error for /usr/pgsql-9.4/include
#- name: Ensure other libraries can see header files
#  file:
#    src: "{{ postgres_install_dir }}/include/"
#    dest: /usr/include/pgsql
#    state: link
#  tags:
#    - postgres_client
#  when: lpgsqlinclude.stat.exists == false

- name: Check if lib link exists
  stat:
    path: /usr/include/pgsql
  register: lpgsqllib

# Error for /usr/pgsql-9.4/include
#- name: Ensure other libraries can see library files
#  file:
#    src: "{{ postgres_install_dir }}/lib"
#    dest: /usr/lib/pgsql
#    state: link
#  tags:
#    - postgres_client
#  when: lpgsqllib.stat.exists == false

- name: Add psql bin directory to path
  template:
    src: postgres.sh.j2
    dest: /etc/profile.d/postgres.sh
    mode: 0644
  tags:
    - postgres_client

# Error for /usr/pgsql-9.4
#- name: Create a symlink that can remain constant during upgrades
#  file:
#    src: "{{ postgres_install_dir }}"
#    dest: /usr/pgsql
#    state: link
#  tags:
#    - postgres_client
